class Autogenerated {
  Data? data;
  bool? status;
  String? stateNum;
  String? message;

  Autogenerated({this.data, this.status, this.stateNum, this.message});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    data = json['data'] != null ? Data.fromJson(json['data']) : null;
    status = json['status'];
    stateNum = json['stateNum'];
    message = json['message'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    data['status'] = status;
    data['stateNum'] = stateNum;
    data['message'] = message;
    return data;
  }
}

class Data {
  int? id;
  String? categoryName;
  List<SubCategoriesPending>? subCategoriesPending;
  List<SubCategoriesAccepted>? subCategoriesAccepted;
  List<SubCategories>? subCategories;

  Data(
      {this.id,
        this.categoryName,
        this.subCategoriesPending,
        this.subCategoriesAccepted,
        this.subCategories});

  Data.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    categoryName = json['categoryName'];
    if (json['subCategoriesPending'] != null) {
      subCategoriesPending = <SubCategoriesPending>[];
      json['subCategoriesPending'].forEach((v) {
        subCategoriesPending!.add(SubCategoriesPending.fromJson(v));
      });
    }
    if (json['subCategoriesAccepted'] != null) {
      subCategoriesAccepted = <SubCategoriesAccepted>[];
      json['subCategoriesAccepted'].forEach((v) {
        subCategoriesAccepted!.add(SubCategoriesAccepted.fromJson(v));
      });
    }
    if (json['subCategories'] != null) {
      subCategories = <SubCategories>[];
      json['subCategories'].forEach((v) {
        subCategories!.add(SubCategories.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['categoryName'] = categoryName;
    if (subCategoriesPending != null) {
      data['subCategoriesPending'] =
          subCategoriesPending!.map((v) => v.toJson()).toList();
    }
    if (subCategoriesAccepted != null) {
      data['subCategoriesAccepted'] =
          subCategoriesAccepted!.map((v) => v.toJson()).toList();
    }
    if (subCategories != null) {
      data['subCategories'] =
          subCategories!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class SubCategoriesPending {
  int? id;
  Title? title;
  Title? description;
  int? price;
  int? shopId;
  int? categoryId;
  int? active;
  int? isPrimary;
  String? imageUrl;
  int? isApproval;
  int? quantity;
  String? createdAt;
  String? updatedAt;
  Pivot? pivot;

  SubCategoriesPending(
      {this.id,
        this.title,
        this.description,
        this.price,
        this.shopId,
        this.categoryId,
        this.active,
        this.isPrimary,
        this.imageUrl,
        this.isApproval,
        this.quantity,
        this.createdAt,
        this.updatedAt,
        this.pivot});

  SubCategoriesPending.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'] != null ? Title.fromJson(json['title']) : null;
    description = json['description'] != null
        ? Title.fromJson(json['description'])
        : null;
    price = json['price'];
    shopId = json['shop_id'];
    categoryId = json['category_id'];
    active = json['active'];
    isPrimary = json['is_primary'];
    imageUrl = json['image_url'];
    isApproval = json['is_approval'];
    quantity = json['quantity'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    pivot = json['pivot'] != null ? Pivot.fromJson(json['pivot']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    if (title != null) {
      data['title'] = title!.toJson();
    }
    if (description != null) {
      data['description'] = description!.toJson();
    }
    data['price'] = price;
    data['shop_id'] = shopId;
    data['category_id'] = categoryId;
    data['active'] = active;
    data['is_primary'] = isPrimary;
    data['image_url'] = imageUrl;
    data['is_approval'] = isApproval;
    data['quantity'] = quantity;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    if (pivot != null) {
      data['pivot'] = pivot!.toJson();
    }
    return data;
  }
}
class SubCategoriesAccepted {
  int? id;
  Title? title;
  Title? description;
  int? price;
  int? shopId;
  int? categoryId;
  int? active;
  int? isPrimary;
  String? imageUrl;
  int? isApproval;
  int? quantity;
  String? createdAt;
  String? updatedAt;
  Pivot? pivot;

  SubCategoriesAccepted(
      {this.id,
        this.title,
        this.description,
        this.price,
        this.shopId,
        this.categoryId,
        this.active,
        this.isPrimary,
        this.imageUrl,
        this.isApproval,
        this.quantity,
        this.createdAt,
        this.updatedAt,
        this.pivot});

  SubCategoriesAccepted.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'] != null ? Title.fromJson(json['title']) : null;
    description = json['description'] != null
        ? Title.fromJson(json['description'])
        : null;
    price = json['price'];
    shopId = json['shop_id'];
    categoryId = json['category_id'];
    active = json['active'];
    isPrimary = json['is_primary'];
    imageUrl = json['image_url'];
    isApproval = json['is_approval'];
    quantity = json['quantity'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    pivot = json['pivot'] != null ? Pivot.fromJson(json['pivot']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    if (title != null) {
      data['title'] = title!.toJson();
    }
    if (description != null) {
      data['description'] = description!.toJson();
    }
    data['price'] = price;
    data['shop_id'] = shopId;
    data['category_id'] = categoryId;
    data['active'] = active;
    data['is_primary'] = isPrimary;
    data['image_url'] = imageUrl;
    data['is_approval'] = isApproval;
    data['quantity'] = quantity;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    if (pivot != null) {
      data['pivot'] = pivot!.toJson();
    }
    return data;
  }
}
class SubCategories {
  int? id;
  Title? title;
  Title? description;
  int? price;
  int? shopId;
  int? categoryId;
  int? active;
  int? isPrimary;
  String? imageUrl;
  int? isApproval;
  int? quantity;
  String? createdAt;
  String? updatedAt;
  Pivot? pivot;

  SubCategories(
      {this.id,
        this.title,
        this.description,
        this.price,
        this.shopId,
        this.categoryId,
        this.active,
        this.isPrimary,
        this.imageUrl,
        this.isApproval,
        this.quantity,
        this.createdAt,
        this.updatedAt,
        this.pivot});

  SubCategories.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'] != null ? Title.fromJson(json['title']) : null;
    description = json['description'] != null
        ? Title.fromJson(json['description'])
        : null;
    price = json['price'];
    shopId = json['shop_id'];
    categoryId = json['category_id'];
    active = json['active'];
    isPrimary = json['is_primary'];
    imageUrl = json['image_url'];
    isApproval = json['is_approval'];
    quantity = json['quantity'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    pivot = json['pivot'] != null ? Pivot.fromJson(json['pivot']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    if (title != null) {
      data['title'] = title!.toJson();
    }
    if (description != null) {
      data['description'] = description!.toJson();
    }
    data['price'] = price;
    data['shop_id'] = shopId;
    data['category_id'] = categoryId;
    data['active'] = active;
    data['is_primary'] = isPrimary;
    data['image_url'] = imageUrl;
    data['is_approval'] = isApproval;
    data['quantity'] = quantity;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    if (pivot != null) {
      data['pivot'] = pivot!.toJson();
    }
    return data;
  }
}

class Title {
  String? en;
  String? ar;

  Title({this.en, this.ar});

  Title.fromJson(Map<String, dynamic> json) {
    en = json['en'];
    ar = json['ar'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['en'] = en;
    data['ar'] = ar;
    return data;
  }
}




class Pivot {
  int? shopId;
  int? subCategoryId;
  String? price;
  int ?quantity;
  String ?isShow;

  Pivot({this.shopId, this.subCategoryId, this.price, this.quantity});

  Pivot.fromJson(Map<String, dynamic> json) {
    shopId = json['shop_id'];
    subCategoryId = json['sub_category_id'];
    price = json['price'];
    quantity = json['quantity'];
    isShow = json['is_show'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['shop_id'] = shopId;
    data['sub_category_id'] = subCategoryId;
    data['price'] = price;
    data['quantity'] = quantity;
    data['is_show'] = isShow;
    return data;
  }
}
