class Autogenerated {
  Data? data;
  bool? status;
  String? stateNum;
  String? message;

  Autogenerated({this.data, this.status, this.stateNum, this.message});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    data = json['data'] != null ? Data.fromJson(json['data']) : null;
    status = json['status'];
    stateNum = json['stateNum'];
    message = json['message'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    data['status'] = status;
    data['stateNum'] = stateNum;
    data['message'] = message;
    return data;
  }
}

class Data {
  DeliveryBoy? deliveryBoy;
  String? token;

  Data({this.deliveryBoy, this.token});

  Data.fromJson(Map<String, dynamic> json) {
    deliveryBoy = json['deliveryBoy'] != null
        ? DeliveryBoy.fromJson(json['deliveryBoy'])
        : null;
    token = json['token'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (deliveryBoy != null) {
      data['deliveryBoy'] = deliveryBoy!.toJson();
    }
    data['token'] = token;
    return data;
  }
}

class DeliveryBoy {
  Name? name;
  String? carNumber;
  String? mobile;
  String? password;
  int? categoryId;
  int? shopId;
  int? isOffline;
  int? isApproval;
  String? drivingLicense;
  String? avatarUrl;
  String? email;
  String? updatedAt;
  String? createdAt;
  int? id;
  Category? category;

  DeliveryBoy(
      {this.name,
        this.carNumber,
        this.mobile,
        this.password,
        this.categoryId,
        this.shopId,
        this.isOffline,
        this.isApproval,
        this.drivingLicense,
        this.avatarUrl,
        this.email,
        this.updatedAt,
        this.createdAt,
        this.id,
        this.category});

  DeliveryBoy.fromJson(Map<String, dynamic> json) {
    name = json['name'] != null ? Name.fromJson(json['name']) : null;
    carNumber = json['car_number'];
    mobile = json['mobile'];
    password = json['password'];
    categoryId = json['category_id'];
    shopId = json['shop_id'];
    isOffline = json['is_offline'];
    isApproval = json['is_approval'];
    drivingLicense = json['driving_license'];
    avatarUrl = json['avatar_url'];
    email = json['email'];
    updatedAt = json['updated_at'];
    createdAt = json['created_at'];
    id = json['id'];
    category = json['category'] != null
        ? Category.fromJson(json['category'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (name != null) {
      data['name'] = name!.toJson();
    }
    data['car_number'] = carNumber;
    data['mobile'] = mobile;
    data['password'] = password;
    data['category_id'] = categoryId;
    data['shop_id'] = shopId;
    data['is_offline'] = isOffline;
    data['is_approval'] = isApproval;
    data['driving_license'] = drivingLicense;
    data['avatar_url'] = avatarUrl;
    data['email'] = email;
    data['updated_at'] = updatedAt;
    data['created_at'] = createdAt;
    data['id'] = id;
    if (category != null) {
      data['category'] = category!.toJson();
    }
    return data;
  }
}

class Name {
  String? en;
  String? ar;

  Name({this.en, this.ar});

  Name.fromJson(Map<String, dynamic> json) {
    en = json['en'];
    ar = json['ar'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['en'] = en;
    data['ar'] = ar;
    return data;
  }
}

class Category {
  int? id;
  Name? title;
  Name? description;
  double? commesion;
  String? imageUrl;
  String? type;
  int? deliveryFee;
  double? expeditedFees;
  double ?schedulerFees;
  String? startWorkTime;
  String? endWorkTime;
  int? active;
  String? createdAt;
  String? updatedAt;

  Category(
      {this.id,
        this.title,
        this.description,
        this.commesion,
        this.imageUrl,
        this.type,
        this.deliveryFee,
        this.expeditedFees,
        this.schedulerFees,
        this.startWorkTime,
        this.endWorkTime,
        this.active,
        this.createdAt,
        this.updatedAt});

  Category.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'] != null ? Name.fromJson(json['title']) : null;
    description = json['description'] != null
        ? Name.fromJson(json['description'])
        : null;
    commesion = json['commesion'];
    imageUrl = json['image_url'];
    type = json['type'];
    deliveryFee = json['delivery_fee'];
    expeditedFees = json['expedited_fees'];
    schedulerFees = json['scheduler_fees'];
    startWorkTime = json['start_work_time'];
    endWorkTime = json['end_work_time'];
    active = json['active'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    if (title != null) {
      data['title'] = title!.toJson();
    }
    if (description != null) {
      data['description'] = description!.toJson();
    }
    data['commesion'] = commesion;
    data['image_url'] = imageUrl;
    data['type'] = type;
    data['delivery_fee'] = deliveryFee;
    data['expedited_fees'] = expeditedFees;
    data['scheduler_fees'] = schedulerFees;
    data['start_work_time'] = startWorkTime;
    data['end_work_time'] = endWorkTime;
    data['active'] = active;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    return data;
  }
}
